FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY src/WorkshopTracker.API/*.csproj ./src/WorkshopTracker.API/
RUN dotnet restore ./src/WorkshopTracker.API/WorkshopTracker.API.csproj

COPY . .
RUN dotnet publish ./src/WorkshopTracker.API/WorkshopTracker.API.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .

ENTRYPOINT ["dotnet", "WorkshopTracker.API.dll"]